#!/bin/bash

mkdir -p "${TRIM_PKGVAR}/ui"
if [ ! -f "${TRIM_PKGVAR}/config.yaml" ]; then
  cp "${TRIM_APPDEST}/defaults/config.yaml" "${TRIM_PKGVAR}/config.yaml"
  chmod 600 "${TRIM_PKGVAR}/config.yaml"
fi
cp -R "${TRIM_APPDEST}/zashboard/." "${TRIM_PKGVAR}/ui/"
exit 0
